### ISSUE TITLE
Please publish the new version to NPM

### ISSUE THREAD

**Issue by Tzelon** [ryb73/bs-qs#2]
Installing:
npm install bs-qs

The src directory contains qs.re file 
with this content 
`module type ParserSchema = {
    type t;
};

module MakeParser = fun (Schema : ParserSchema) => {
    external parse : string => Js.t Schema.t = "parse" [@@bs.module "qs"];
};

external stringify : Js.t {..} => string = "stringify" [@@bs.module "qs"];`

**Comment by ryb73** [comment]
Sorry for the delay. A new version has been published to npm under @ryb73/bs-qs
